[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-rs run --chip RP2040"
# the line below will load & start a serial monitor, but unfortunately that serial monitor doesn't allow input
#runner = "elf2uf2-rs --deploy --serial --verbose"
runner = "elf2uf2-rs --deploy --verbose"

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

# [unstable]
# nicer workspace inheritance for lints/dep overrides (optional)

[env]
DEFMT_LOG = "debug"

#[profile.release]
#codegen-units = 1
#lto = true

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 'z'
strip = true  # Automatically strip symbols from the binary.


[profile.dev]
debug = 2
lto = true
opt-level = "z"